import '@/styles/globals.css';

// next
import type {Metadata} from 'next';

// libraries
import {config} from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

// components
import LayoutHeader from '@/app/(layout)/components/LayoutHeader';
import LayoutSide from '@/app/(layout)/components/LayoutSide';

// providers
import AuthProvider from '@/providers/next-auth/AuthProvider';

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="w-screen h-screen bg-B400 text-white">
        <AuthProvider>
          <div className="flex justify-center">
            {/* side */}
            <LayoutSide />

            {/* content */}
            <div className="flex basis-[900px] p-5">{children}</div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: 'PAFC',
  description: 'Generated by create next app'
};
