import "@/styles/globals.css";

// next
import type { Metadata } from "next";

// libraries
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

// components
import LayoutHeader from "@/app/(layout)/components/LayoutHeader";
import LayoutSide from "@/app/(layout)/components/LayoutSide";

// providers
import AuthProvider from "@/providers/next-auth/AuthProvider";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-B400">
        <AuthProvider>
          <LayoutSide />
        </AuthProvider>
      </body>
    </html>
  );
};

export const metadata: Metadata = {
  title: "PAFC",
  description: "Generated by create next app",
};
